import { orderSchema, type Order } from "@/schemas/order.schema";
import { tenantClient, unwrap } from "./service-utils";
import type { CartItem } from "@/schemas/cart.schema";
import type { CheckoutInput } from "@/schemas/order.schema";
import type { OrderStatus } from "@/schemas/order.schema";
export async function listOrders(tenantId: string, userId: string): Promise<Order[]> { const { supabase } = await tenantClient(tenantId); const result = unwrap(await supabase.from("orders").select("*").eq("tenant_id", tenantId).eq("user_id", userId).order("created_at", { ascending: false })); return (result as unknown[]).map((row) => orderSchema.parse(row)); }
function mapOrder(row: Record<string, unknown>): Order {
    return orderSchema.parse({ ...row, orderNumber: row.order_number ?? row.orderNumber, userId: row.user_id ?? row.userId, tenantId: row.tenant_id, items: row.items, shippingAddress: row.shipping_address ?? row.shippingAddress, paymentMethod: row.payment_method ?? row.paymentMethod, paymentStatus: row.payment_status ?? row.paymentStatus, orderStatus: row.order_status ?? row.orderStatus, shippingFee: row.shipping_fee ?? row.shippingFee, discountAmount: row.discount_amount ?? row.discountAmount, createdAt: row.created_at ?? row.createdAt, updatedAt: row.updated_at ?? row.updatedAt });
}
export async function listTenantOrders(tenantId: string): Promise<Order[]> { const { supabase } = await tenantClient(tenantId); const rows = unwrap(await supabase.from("orders").select("*").eq("tenant_id", tenantId).order("created_at", { ascending: false })); return (rows as Record<string, unknown>[]).map(mapOrder); }
export async function getDashboardStats(tenantId: string) { const { supabase } = await tenantClient(tenantId); const [ordersResult, productsResult] = await Promise.all([supabase.from("orders").select("id,total,order_status,created_at,order_number,shipping_address", { count: "exact" }).eq("tenant_id", tenantId).order("created_at", { ascending: false }), supabase.from("products").select("id", { count: "exact", head: true }).eq("tenant_id", tenantId)]); if (ordersResult.error) throw new Error(ordersResult.error.message); if (productsResult.error) throw new Error(productsResult.error.message); const orders = (ordersResult.data ?? []) as Array<Record<string, unknown>>; const revenue = orders.filter((order) => ['completed', 'delivered'].includes(String(order.order_status).toLowerCase())).reduce((sum, order) => sum + Number(order.total ?? 0), 0); return { revenue, ordersCount: ordersResult.count ?? orders.length, productsCount: productsResult.count ?? 0, recentOrders: orders.slice(0, 7).map((row) => ({ id: String(row.id), orderNumber: String(row.order_number ?? row.id), total: Number(row.total ?? 0), status: String(row.order_status ?? 'pending'), createdAt: String(row.created_at ?? ''), customerName: typeof row.shipping_address === 'object' && row.shipping_address !== null ? String((row.shipping_address as Record<string, unknown>).fullName ?? '') : '' })) }; }
export async function updateTenantOrderStatus(tenantId: string, orderId: string, orderStatus: OrderStatus): Promise<Order> { const { supabase } = await tenantClient(tenantId); const result = await supabase.from("orders").update({ order_status: orderStatus, tenant_id: tenantId }).eq("tenant_id", tenantId).eq("id", orderId).select(); if (result.error) throw new Error(result.error.message); const row = result.data?.[0]; if (!row) throw new Error("Order was not found or could not be updated"); return mapOrder(row as Record<string, unknown>); }
export async function createOrder(tenantId: string, userId: string, input: Order): Promise<Order> { const { supabase } = await tenantClient(tenantId); return orderSchema.parse(unwrap(await supabase.from("orders").insert({ ...input, tenant_id: tenantId, user_id: userId }).select().single())); }
export async function checkoutCart(tenantId: string, items: CartItem[], input: CheckoutInput): Promise<{ orderId: string; orderNumber: string }> {
    const { supabase } = await tenantClient(tenantId);
    const result = await supabase.rpc("checkout_cart", { p_tenant_id: tenantId, p_items: items, p_shipping_address: input.shippingAddress, p_payment_method: input.paymentMethod, p_notes: input.notes ?? null });
    if (result.error) throw new Error(result.error.message);
    const row = Array.isArray(result.data) ? result.data[0] : result.data;
    if (!row?.order_id || !row?.order_number) throw new Error("Order creation returned no confirmation");
    return { orderId: row.order_id, orderNumber: row.order_number };
}
