create extension if not exists pgcrypto;

do $$ begin create type public.user_role as enum ('customer','assistant','admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.account_status as enum ('active','suspended','pending'); exception when duplicate_object then null; end $$;
do $$ begin create type public.order_status as enum ('pending','processing','shipped','delivered','cancelled','refunded'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_status as enum ('pending','paid','failed','refunded'); exception when duplicate_object then null; end $$;
do $$ begin create type public.payment_method as enum ('cod','card','wallet'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, tenant_id uuid not null, email text not null, full_name text not null, phone text, avatar_url text, role public.user_role not null default 'customer', status public.account_status not null default 'active', is_email_verified boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.categories (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, name text not null, slug text not null, description text, image text, parent_id uuid references public.categories(id) on delete set null, unique (tenant_id, slug));
create table if not exists public.products (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, title text not null, slug text not null, description text not null, price numeric(12,2) not null check (price > 0), compare_at_price numeric(12,2), images jsonb not null default '[]', colors jsonb not null default '[]', tags jsonb not null default '[]', category_id uuid references public.categories(id) on delete set null, variants jsonb not null default '[]', rating numeric(3,2) not null default 0 check (rating between 0 and 5), reviews_count integer not null default 0, in_stock boolean not null default true, is_featured boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (tenant_id, slug));
create table if not exists public.coupons (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, code text not null, discount_type text not null check (discount_type in ('percentage','fixed_amount')), discount_value numeric(12,2) not null check (discount_value > 0), min_order_amount numeric(12,2) not null default 0, max_discount_amount numeric(12,2), expires_at timestamptz, is_active boolean not null default true, unique (tenant_id, code));
create table if not exists public.carts (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, user_id uuid not null references auth.users(id) on delete cascade, items jsonb not null default '[]', summary jsonb not null default '{}', updated_at timestamptz not null default now(), unique (tenant_id, user_id));
create table if not exists public.wishlists (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, user_id uuid not null references auth.users(id) on delete cascade, product_id uuid not null references public.products(id) on delete cascade, created_at timestamptz not null default now(), unique (tenant_id, user_id, product_id));
create table if not exists public.orders (id uuid primary key default gen_random_uuid(), tenant_id uuid not null, user_id uuid not null references auth.users(id) on delete restrict, order_number text not null, items jsonb not null, shipping_address jsonb not null, payment_method public.payment_method not null, payment_status public.payment_status not null default 'pending', order_status public.order_status not null default 'pending', subtotal numeric(12,2) not null check (subtotal >= 0), shipping_fee numeric(12,2) not null default 0 check (shipping_fee >= 0), discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0), total numeric(12,2) not null check (total >= 0), notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (tenant_id, order_number));
create table if not exists public.tenant_memberships (user_id uuid not null references auth.users(id) on delete cascade, tenant_id uuid not null, role text not null, status text not null, primary key (user_id, tenant_id));

create index if not exists products_tenant_created_idx on public.products (tenant_id, created_at desc); create index if not exists categories_tenant_name_idx on public.categories (tenant_id, name); create index if not exists coupons_tenant_code_idx on public.coupons (tenant_id, code); create index if not exists orders_tenant_user_idx on public.orders (tenant_id, user_id, created_at desc); create index if not exists wishlists_tenant_user_idx on public.wishlists (tenant_id, user_id);

do $$ declare t text; begin foreach t in array array['profiles','categories','products','coupons','carts','wishlists','orders','tenant_memberships'] loop execute format('alter table public.%I enable row level security', t); execute format('drop policy if exists tenant_isolation on public.%I', t); execute format('create policy tenant_isolation on public.%I using (tenant_id::text = (auth.jwt() ->> ''tenant_id'')) with check (tenant_id::text = (auth.jwt() ->> ''tenant_id''))', t); end loop; end $$;
create policy profiles_self on public.profiles for all using (id = auth.uid()) with check (id = auth.uid());
create policy carts_self on public.carts for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy wishlists_self on public.wishlists for all using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy orders_self on public.orders for select using (user_id = auth.uid());
